generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        sf_guard_user

    config:
      actions: ~
      fields:  ~
      list:
        display:          [username, name, lastname, is_active, is_super_admin]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~