generator:
  class: sfPropelGenerator
  param:
    model_class:           NewsArticle
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              NewsArticle
    plural:                NewsArticles
    route_prefix:          news_article
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        news_article
    
    config:
      actions: ~
      fields:  ~
      list:
        peer_method:      doSelectWithI18n
        display:          [headline, publish_date, enter_date, exit_date, is_published]
        sort:             [publish_date, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~