newSuccess:
  stylesheets: ['datepicker.css']
  javascripts: ['datepicker.js', 'date.js', "tiny_mce/jquery.tinymce.js", "tiny_mce/tiny_mce.js", "textarea.js"]
editSuccess:
  stylesheets: ['datepicker.css']
  javascripts: ['datepicker.js', 'date.js', "tiny_mce/jquery.tinymce.js", "tiny_mce/tiny_mce.js", "textarea.js"]
all:
  layout: mfAdminLayout