# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
default:
  http_metas:
    content-type: text/html

  metas:
    title:        Área de administração monicet
    description:  Área de administração do projecto monicet
    keywords:     administração, monicet, cetáceos, morfose, baleias
    language:     pt
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  components:
    menu:         [main, menu]
  
  has_layout:     true
  layout:         layout