# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
default:
  http_metas:
    content-type: text/html

  metas:
    title:        Área de administração monicet
    description:  Área de administração do projecto monicet
    keywords:     administração, monicet, cetáceos, morfose, baleias
    language:     pt
    robots:       index, follow

  stylesheets:    [/mfAdministracaoPlugin/css/resetfontsgrids, /mfAdministracaoPlugin/css/layout, /mfAdministracaoPlugin/css/default, /mfAdministracaoPlugin/css/dropdown/dropdown, "/mfAdministracaoPlugin/css/dropdown/morfose/default.advanced.css", "jquery.modal.css", "jquery.tooltip.css", main]

  javascripts:    ["jquery-1.4.min.js", "jquery.modal.js", "jquery.tooltip.js", main]

  components:
    menu:         [main, menu]
  
  has_layout:     true
  layout:         layout
  