generator:
  class: sfPropelGenerator
  param:
    model_class:           Sighting
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Sighting
    plural:                Sightings
    route_prefix:          sighting
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        sighting
    
    config:
      actions: ~
      fields:  ~
      list:
        display:           [record, specie, behaviour, association, adults, juveniles, cubs]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
