# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: language }

language:
  url:   /:sf_culture
  param: { module: home, action: index }
  requirements:
    sf_culture: (?:pt|en)

news_all:
  url:      /:sf_culture/news/all
  param:    { module: news, action: all }

news:
  url:      /:sf_culture/news/:slug
  class:    sfPropelRoute
  param:    { module: news, action: show }
  options:  { model: NewsArticle, type: object }

consorcium:
  url:      /:sf_culture/consorcium/:slug
  class:    sfPropelRoute
  param:    { module: consorcium, action: show }
  options:  { model: ConsorciumElement, type: object }

default_index:
  url:   /:sf_culture/:module
  param: { action: index }