# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: language, sf_culture: en }

index:
  url:   /:sf_culture
  param: { module: home, action: index }
  requirements:
    sf_culture: (?:pt|en)

background:
  url:      /:sf_culture/background
  param:    { module: background, action: index }

news_all:
  url:      /:sf_culture/news/all
  param:    { module: news, action: all }

news:
  url:      /:sf_culture/news/:slug
  class:    sfPropelRoute
  param:    { module: news, action: show }
  options:  { model: NewsArticle, type: object }

news_feeds:
  url:      /:sf_culture/feeds
  param:    { module: feeds, action: latest }

consorcium:
  url:      /:sf_culture/consorcium/:slug
  class:    sfPropelRoute
  param:    { module: consorcium, action: show }
  options:  { model: ConsorciumElement, type: object }

team:
  url:      /:sf_culture/team/:slug
  class:    sfPropelRoute
  param:    { module: team, action: show }
  options:  { model: Team, type: object }

contacts:
  url:      /:sf_culture/contacts
  param:    { module: contacts, action: index }

default_index:
  url:   /:sf_culture/:module
  param: { action: index }