generator:
  class: sfPropelGenerator
  param:
    model_class:           WatchVisibility
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              WatchVisibility
    plural:                WatchVisibilitys
    route_prefix:          watch_visibility
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        watch_visibility

    config:
      actions: ~
      fields:  
        descriptionPt:
          label: "Descrição (PT)"
        descriptionEn:
          label: "Descrição (EN)"
      list:    
        display:          [code, _descriptionPt, _descriptionEn]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
