generator:
  class: sfPropelGenerator
  param:
    model_class:           WatchSighting
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              WatchSighting
    plural:                WatchSightings
    route_prefix:          watch_sighting
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
