indexSuccess:
  stylesheets: [ "jquery-theme/jquery-ui-1.8.6.custom.css", 'datepicker.css', "monicet_maps_default.css", "jquery-theme/jquery-ui-1.8.6.custom.css", "monicet_maps_right_sidebar.css", "container_layout.css" ]
  javascripts: [-*, "jquery-1.4.2.min.js", "jquery-ui-1.8.6.custom.min.js", 'datepicker.js', 'date.js', "jquery.maskedinput-1.2.2.min.js", "http://maps.google.com/maps/api/js?sensor=true", "monicet_maps.js"]
  layout: mfAdminLayout
  
timeSuccess:
  stylesheets: [ "jquery-theme/jquery-ui-1.8.6.custom.css", 'datepicker.css', "monicet_maps_time.css", "jquery-theme/jquery-ui-1.8.6.custom.css", "monicet_maps_right_sidebar.css" ]
  javascripts: [ -*, "timemap/lib/jquery-1.4.4.min.js",  "jquery-ui-1.8.6.custom.min.js", "jquery.maskedinput-1.2.2.min.js", "timemap/lib/mxn/mxn.js?(googlev3)", "timemap/lib/timeline-1.2.js", "timemap/src/timemap.js", "timemap/src/manipulation.js", "http://maps.google.com/maps/api/js?sensor=true", "monicet_maps.js" ]
  layout: mfAdminLayout

auto_completeSuccess:
  has_layout: False
  
get_resultsSuccess:
  has_layout: False