generator:
  class: sfPropelGenerator
  param:
    model_class:           SpecieGroup
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              SpecieGroup
    plural:                SpecieGroups
    route_prefix:          specie_group
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        specie_group

    config:
      actions: ~
      fields:  ~
      list:
        peer_method:       doSelectWithI18n
        display:           [name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
