generator:
  class: sfPropelGenerator
  param:
    model_class:           Guide
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Guide
    plural:                Guides
    route_prefix:          guide
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        guide

    config:
      actions: ~
      fields:  ~
      list:
        display:           [company, name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
