generator:
  class: sfPropelGenerator
  param:
    model_class:           ConsorciumElement
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ConsorciumElement
    plural:                ConsorciumElements
    route_prefix:          consorcium_element
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
