newSuccess:
  stylesheets: []
  javascripts: ["tiny_mce/jquery.tinymce.js", "tiny_mce/tiny_mce.js", "textarea.js"]
editSuccess:
  stylesheets: []
  javascripts: ["tiny_mce/jquery.tinymce.js", "tiny_mce/tiny_mce.js", "textarea.js"]
all:
  layout: mfAdminLayout