generator:
  class: sfPropelGenerator
  param:
    model_class:           Record
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Record
    plural:                Records
    route_prefix:          record
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        record

    config:
      actions: ~
      fields:  ~
      list:
        display:           [general_info, code, visibility, sea_state, time, show_sightings]
        peer_method:       doSelectByGeneralInfo
        fields:
          id:  ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
    