lineSuccess:
  javascripts: [-*, "jquery-1.4.min.js", "jquery-ui-1.8.1-custom.min.js"]
  has_layout: False
helpSuccess:
  has_layout: False
lineSubmitSuccess:
  has_layout: False
all:
  layout: mfAdminLayout
guardarLinhaSuccess:
  javascripts: [-*, "jquery-1.4.min.js", "jquery-ui-1.8.1-custom.js"]
  has_layout: False