propel:
  news_article:
    _attributes:   { isI18N: true, i18nTable: news_article_i18n }
    id:            ~
    is_published:  { type: boolean, required: true, default: 0 }
    slug:          { type: varchar(255), required: true, index: unique }
    image:         { type: varchar(1024), required: false}
    enter_date:    { type: date }
    exit_date:     { type: date }
    publish_date:  { type: date, required: true }
    created_at:    ~
    updated_at:    ~
  news_article_i18n:
    id:            { type: integer, required: true, primaryKey: true, foreignTable: news_article, foreignReference: id, onDelete: cascade }
    culture:       { isCulture: true, type: varchar(7), required: true, primaryKey: true }
    headline:      { type: varchar(255), required: true }
    body:          { type: longvarchar, required: true }
  consorcium_element:
    _attributes:   { isI18N: true, i18nTable: consorcium_element_i18n }
    id:            ~
    name:          { type: varchar(255), required: true }
    logotype:      { type: varchar(255), required: false }
    link:          { type: varchar(500), required: false }
    slug:          { type: varchar(255), required: true, index: unique }
    created_at:    ~
    updated_at:    ~
  consorcium_element_i18n:
    id:            { type: integer, required: true, primaryKey: true, foreignTable: consorcium_element, foreignReference: id, onDelete: cascade }
    culture:       { isCulture: true, type: varchar(7), required: true, primaryKey: true }
    description:   { type: longvarchar, required: false }
  team:
    _attributes:   { isI18N: true, i18nTable: team_i18n }
    id:            ~
    slug:          { type: varchar(255), required: true, index: unique }
    type:          { type: varchar(255), required: true }
    name:          { type: varchar(512), required: true }
    link:          { type: varchar(1024), required: false }
    photo:         { type: varchar(1024), required: false }
    created_at:    ~
    updated_at:    ~
  team_i18n:
    id:            { type: integer, required: true, primaryKey: true, foreignTable: team, foreignReference: id, onDelete: cascade }
    culture:       { isCulture: true, type: varchar(7), required: true, primaryKey: true }
    about:         { type: longvarchar, required: false }
  album:
    _attributes:   { isI18N: true, i18nTable: album_i18n }
    id:            ~
    slug:          { type: varchar(255), required: true, index: unique }
    is_public:     { type: boolean, default: false, required: false }
    created_at:    ~
    updated_at:    ~
  album_i18n:
    id:            { type: integer, required: true, primaryKey: true, foreignTable: album, foreignReference: id, onDelete: cascade }
    culture:       { isCulture: true, type: varchar(7), required: true, primaryKey: true }
    name:          { type: varchar(512), required: true }
  photo:
    _attributes:   { isI18N: true, i18nTable: photo_i18n }
    id:            ~
    slug:          { type: varchar(255), required: true, index: unique }
    album_id:      { type: integer, foreignTable: album, foreignReference: id, required: true, onDelete: cascade }
    image:         { type: varchar(1024), required: false}
    created_at:    ~
    updated_at:    ~
  photo_i18n:
    id:            { type: integer, required: true, primaryKey: true, foreignTable: photo, foreignReference: id, onDelete: cascade }
    culture:       { isCulture: true, type: varchar(7), required: true, primaryKey: true }
    caption:       { type: varchar(512), required: true }
