propel:
   company:
      id:               ~
      name:             { type: varchar(255), required: true }
      acronym:          { type: varchar(45), required: true }
      base_latitude:    { type: varchar(45), required: true }
      base_longitude:   { type: varchar(45), required: true }
      url:              { type: varchar, size: 255 }
      telephone:        { type: varchar, size: 30 }
      mobile:           { type: varchar, size: 30 }
      fax:              { type: varchar, size: 30 }
      email:            { type: varchar, size: 255 }
      address:          { type: longvarchar, size: 255 }
      zipcode:          { type: varchar, size: 8 }
      district:         { type: varchar, size: 255 }
      municipality:     { type: varchar, size: 255 }
      locality:         { type: varchar, size: 255 }
      observations:     { type: longvarchar }
      created_at:       ~
      updated_at:       ~
  
   company_user:
      company_id:       { type: integer, primaryKey: true, foreignTable: company, foreignReference: id, required: true, onDelete: cascade }
      user_id:          { type: integer, primaryKey: true, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
      created_at:       ~
      updated_at:       ~

   vessel:
      id:               ~
      company_id:       { type: integer, foreignTable: company, foreignReference: id, required: true, onDelete: cascade }
      name:             { type: varchar(255), required: true }
      length:           { type: integer, required: false }
      power:            { type: float, required: false }
      height:           { type: float, required: false }
      observations:     { type: longvarchar }      
      created_at:       ~
      updated_at:       ~

   guide:
      id:               ~
      company_id:       { type: integer, foreignTable: company, foreignReference: id, required: true, onDelete: cascade }
      name:             { type: varchar(255), required: true }
      observations:     { type: longvarchar }
      created_at:       ~
      updated_at:       ~

   skipper:
      id:               ~
      company_id:       { type: integer, foreignTable: company, foreignReference: id, required: true, onDelete: cascade }
      name:             { type: varchar(255), required: true }
      observations:     { type: longvarchar }
      created_at:       ~
      updated_at:       ~

   general_info:
      id:               ~
      code:             { type: varchar(45), required: true }
      vessel_id:        { type: integer, foreignTable: vessel, foreignReference: id, required: false }
      skipper_id:       { type: integer, foreignTable: skipper, foreignReference: id, required: false, onDelete: cascade }
      guide_id:         { type: integer, foreignTable: guide, foreignReference: id, required: false, onDelete: cascade }
      company_id:       { type: integer, foreignTable: company, foreignReference: id, required: true, onDelete: cascade }
      base_latitude:    { type: varchar(45), required: true }
      base_longitude:   { type: varchar(45), required: true }
      date:             { type: date, required: true }
      valid:            { type: boolean, required: true }
      comments:         { type: longvarchar, required: false }
      created_by:       { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
      updated_by:       { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
      created_at:       ~
      updated_at:       ~


   visibility:
      id:               ~
      code:             { type: integer, required: true, index: unique }
      description:      { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   sea_state:
      id:               ~
      code:             { type: integer, required: true, index: unique }
      description:      { type: varchar, size: 255, required: true }
      created_at:       ~
      updated_at:       ~

   code:
      id:               ~
      acronym:          { type: varchar(10), required: true }
      description:      { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   record:
      id:               ~
      code_id:          { type: integer, foreignTable: code, foreignReference: id, required: true, onDelete: cascade }
      visibility_id:    { type: integer, foreignTable: visibility, foreignReference: id, required: true, onDelete: cascade }
      sea_state_id:     { type: integer, foreignTable: sea_state, foreignReference: id, required: true, onDelete: cascade }
      general_info_id:  { type: integer, foreignTable: general_info, foreignReference: id, required: true, onDelete: cascade }
      time:             { type: time, required: true }
      latitude:         { type: varchar(45), required: true }
      longitude:        { type: varchar(45), required: true }
      num_vessels:      { type: integer, default: 0, required: false }
      created_at:       ~
      updated_at:       ~

   association:
      id:               ~
      code:             { type: integer, required: true, index: unique }
      description:      { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   behaviour:
      id:               ~
      code:             { type: integer, required: true, index: unique }
      description:      { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   specie_group:
      id:               ~
      name:             { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   specie:
      id:               ~
      specie_group_id:  { type: integer, foreignTable: specie_group, foreignReference: id, required: true, onDelete: cascade }
      code:             { type: varchar(10), required: true }
      name:             { type: varchar(255), required: true }
      created_at:       ~
      updated_at:       ~

   sighting:
      id:               ~
      record_id:        { type: integer, foreignTable: record, foreignReference: id, required: true, onDelete: cascade }
      specie_id:        { type: integer, foreignTable: specie, foreignReference: id, required: false, onDelete: cascade }
      behaviour_id:     { type: integer, foreignTable: behaviour, foreignReference: id, required: false, onDelete: cascade }
      association_id:   { type: integer, foreignTable: association, foreignReference: id, required: false, onDelete: cascade }
      adults:           { type: varchar(45), required: false }
      juveniles:        { type: varchar(45), required: false }
      cubs:             { type: varchar(45), required: false }
      total:            { type: integer, required: false }
      number_vessels:   { type: integer, required: false }
      comments:         { type: longvarchar, required: false }
      created_at:       ~
      updated_at:       ~

   user:
      _attributes:        { phpName: User }
      id:                 ~
      user_id:            { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
      name:               { type: varchar, size: 255, required: true }
      birthday:           { type: date }
      bi:                 { type: varchar, size: 30 }
      nif:                { type: varchar, size: 30 }
      country:            { type: varchar, size: 255, default: 'PT' }
      district:           { type: varchar, size: 255 }
      municipality:       { type: varchar, size: 255 }
      locality:           { type: varchar, size: 255 }
      address:            { type: varchar, size: 255 }
      zipcode:            { type: varchar, size: 8 }
      telephone:          { type: varchar, size: 30 }
      mobile:             { type: varchar, size: 30 }
      email:              { type: varchar, size: 255 }
      lang:               { type: varchar, size: 255, default: 'pt' }
      photo:              { type: varchar, size: 255 }
      observations:       { type: longvarchar }
      created_at:         ~
      updated_at:         ~
