generator:
  class: sfPropelGenerator
  param:
    model_class:           WatchInfo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              WatchInfo
    plural:                WatchInfos
    route_prefix:          watch_info
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        watch_info

    config:
      actions: ~
      fields:  
        date:
          date_format:     yyyy-MM-dd
      list:
        display:           [code, date, watch_post, watchman, base_latitude, base_longitude, valid]
        peer_method:       doSelectByCompany
        peer_count_method: doCountByCompany
        object_actions:
          showGrid:        {label: Registos}
          _edit:      ~
          _delete:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
