sheetSuccess:
  stylesheets: [ "jquery-theme/jquery-ui-1.8.6.custom.css", 'datepicker.css', 'layout_watch_info.css' ]
  javascripts: [-*, "jquery-1.4.2.min.js", "jquery-ui-1.8.6.custom.min.js", 'datepicker.js', 'date.js', "jquery.maskedinput-1.2.2.min.js"]

newSuccess:
  javascripts: ['datepicker.js', 'date.js', coordenadas_empresa_vigias.js]
  stylesheets: ['datepicker.css']
  
editSuccess:
  javascripts: ['datepicker.js', 'date.js', coordenadas_empresa_vigias.js]
  stylesheets: ['datepicker.css']

indexSuccess:
  javascripts:  [-*,"jquery-1.4.min.js", "jquery.modal.js", "jquery.tooltip.js", main, "jquery-ui-1.8.6.custom.min.js", jquery.ui.datepicker-pt-BR.min.js, datas.php ]
  stylesheets:  ["jquery-theme/jquery-ui-1.8.6.custom.css" ]

all:
  layout: mfAdminLayout