generator:
  class: sfPropelGenerator
  param:
    model_class:           Visibility
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Visibility
    plural:                Visibilitys
    route_prefix:          visibility
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        visibility

    config:
      actions: ~
      fields:  ~
      list:
        peer_method:       doSelectWithI18n
        display:           [code, description]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
