generator:
  class: sfPropelGenerator
  param:
    model_class:           Specie
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Specie
    plural:                Species
    route_prefix:          specie
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        specie

    config:
      actions: ~
      fields:  ~
      list:
        display:           [specie_group, code, name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
