generator:
  class: sfPropelGenerator
  param:
    model_class:           Specie
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Specie
    plural:                Species
    route_prefix:          specie
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        specie

    config:
      actions: ~
      fields:  
        rec_cet_code:
          label: "Cod. Rec. cetáceos"
        scientific_name:
          label: "Nome científico"
      list:
        peer_method:       doSelectWithI18n
        display:           [specie_group, code, rec_cet_code, scientific_name, name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
