generator:
  class: sfPropelGenerator
  param:
    model_class:           Company
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Company
    plural:                Companys
    route_prefix:          company
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        company

    config:
      actions:
      fields:
        rec_cet_code:
          label: "Cod. Rec. cetáceos"
        acronym:
          label: "Acrónimo"
        zipcode:           { label: Código Postal }
        district:          { label: Distrito }
        municipality:      { label: Conselho }
        observations:      { label: Observações }
      list:
        display:           [acronym, rec_cet_code, name, base_latitude, base_longitude]
        peer_method:       doSelectByCompany
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~