generator:
  class: sfPropelGenerator
  param:
    model_class:           Company
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Company
    plural:                Companys
    route_prefix:          company
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        company

    config:
      actions: ~
      fields:  ~
      list:
        display:           [name, base_latitude, base_longitude]
      filter:  ~
      form:    ~
      edit:
        actions:
          _save:  ~
          _cancel:  ~
          _save_and_add:  ~
          teste:  ~
      new:     ~