generator:
  class: sfPropelGenerator
  param:
    model_class:           Company
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Company
    plural:                Companys
    route_prefix:          company
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        company

    config:
      actions:
      fields:  ~
      list:
        display:           [acronym, name, base_latitude, base_longitude]
        peer_method:       doSelectByCompany
      filter:
        class: false
      form:    ~
      edit:
        actions:
          _save:  ~
          _cancel:  ~
          teste:  ~
      new:     ~