newSuccess:
  javascripts: [-*, "http://maps.google.com/maps/api/js?sensor=true", "jquery-1.4.2.min.js", "jquery-ui-1.8.6.custom.min.js", "jquery.maskedinput-1.2.2.min.js", 'geo.js']
  stylesheets: [ 'company_form.css' ]

editSuccess:
  javascripts: [-*, "http://maps.google.com/maps/api/js?sensor=true", "jquery-1.4.2.min.js", "jquery-ui-1.8.6.custom.min.js", "jquery.maskedinput-1.2.2.min.js", 'geo.js']
  stylesheets: [ 'company_form.css' ]

all:
  layout: mfAdminLayout
