generator:
  class: sfPropelGenerator
  param:
    model_class:           Vessel
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Vessel
    plural:                Vessels
    route_prefix:          vessel
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        vessel

    config:
      actions: ~
      fields:  ~
      list:
        display:           [company, name]
        peer_method:       doSelectByCompany
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
