generator:
  class: sfPropelGenerator
  param:
    model_class:           GeneralInfo
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              GeneralInfo
    plural:                GeneralInfos
    route_prefix:          general_info
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        general_info
    
    config:
      fields:  
        date:
          date_format:     yyyy-MM-dd
      list:
        display:           [code, date, vessel, base_latitude, base_longitude, valid]
        peer_method:       doSelectByCompany
        object_actions:
          showGrid:        {label: Registos}
          showMap:         {label: Ver em Mapa}
          _edit:      ~
          _delete:    ~
      filter:  ~
      form:    ~
      edit:    ~