generator:
  class: sfPropelGenerator
  param:
    model_class:           GeneralInfo
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              GeneralInfo
    plural:                GeneralInfos
    route_prefix:          general_info
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        general_info
    
    config:
      actions: ~
      fields:  ~
      list:
        display:           [vessel, base_latitude, base_longitude, date]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
