sheetSuccess:
  javascripts: ['datepicker.js', 'date.js']
  stylesheets: ['datepicker.css']

newSuccess:
  javascripts: ['datepicker.js', 'date.js']
  stylesheets: ['datepicker.css']

all:
  layout: mfAdminLayout
  