generator:
  class: sfPropelGenerator
  param:
    model_class:           Association
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Association
    plural:                Associations
    route_prefix:          association
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        association

    config:
      actions: ~
      fields:  ~
      list:
        display:           [code, description]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
