generator:
  class: sfPropelGenerator
  param:
    model_class:           WatchBehaviour
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              WatchBehaviour
    plural:                WatchBehaviours
    route_prefix:          watch_behaviour
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        

    config:
      actions: ~
      fields:  ~
      list:
        peer_method:       doSelectWithI18n
        display:           [code, description]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
