generator:
  class: sfPropelGenerator
  param:
    model_class:           Skipper
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Skipper
    plural:                Skippers
    route_prefix:          skipper
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
