generator:
  class: sfPropelGenerator
  param:
    model_class:           WatchCode
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              WatchCode
    plural:                WatchCodes
    route_prefix:          watch_code
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        watch_code

    config:
      actions: ~
      fields:  ~
      list:
        peer_method:       doSelectWithI18n
        display:          [acronym, description]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
